### ISSUE TITLE
[ feat ] Asset Analysis API 작성

### ISSUE THREAD

**Issue by justice-7** [BBYUworld/gagyebbyu-be#16]
## Issue
- 자산 분석 페이지 API 작성

## ToDo List
- [x] 자산 분류 통계 API 작성
- [x] 연도별 자산 테이블 저장
- [ ] 자산 작년대비 증감율 API 작성
- [ ] 지출 카테고리 통계 API 작성
- [ ] 월 평균 소득 API 작성
- [ ] 월 평균 지출 API 작성
