### ISSUE TITLE
[ feat/refactor ] Couple Notification

### ISSUE THREAD

**Issue by bapdung** [BBYUworld/gagyebbyu-be#17]
## ToDo List
- [x] Couple Entity 수정
- [x] Couple 등록 수정
- [x] Couple 요청 api 추가
