### ISSUE TITLE
[ feat ] Asset Analysis API 작성

### ISSUE THREAD

**Issue by justice-7** [BBYUworld/gagyebbyu-be#25]
## Issue
- 자산 분석 API 작성

## ToDo List
- [x] 자산 카테고리 통계 API 작성
- [x] 연도별 자산 API 작성
- [x] 자산 작년대비 증감율 API 작성
- [x] 자산 패턴 분석 (카테고리, 타부부) API 작성
