### ISSUE TITLE
[ feat ] Expense 소비 패턴 분석

### ISSUE THREAD

**Issue by bapdung** [BBYUworld/gagyebbyu-be#27]
## Issue
- category enum 수정
- fundTransaction response 수정 및 entity 수정

## ToDo List
- [x] Expense 최종 소비 패턴 분석
- [x] Expense 카테고리 별 소비량 분석 api
- [x] Expense Month response 수정
- [x] Expense 작년 소비량
- [x] Expense 저번달 소비량

**Comment by bapdung** [comment]
Expense 월간조회 DTO 수정

**Comment by bapdung** [comment]
User Entity 수정

**Comment by bapdung** [comment]
category Repository 수정
