### ISSUE TITLE
[ refactor/feat ] Analysis Fund 수정

### ISSUE THREAD

**Issue by bapdung** [BBYUworld/gagyebbyu-be#69]
## Issue
- 어떠한 문제 해결
- 이러한 문제 해결

## ToDo List
- [x] Fund 카테고리별 통계 월 별 조회로 수정
- [x] Fund 최종 분석 월 별 수정
- [x] Fund category 별 지출 내역 response
