### ISSUE TITLE
[ refactor ] Analysis Expense 스케줄러 수정

### ISSUE THREAD

**Issue by bapdung** [BBYUworld/gagyebbyu-be#87]
## Issue
- md 잘못 건드려서 수정

## ToDo List
- [x] 지출 스케줄러 변경
- [x] 지출분석 entity 및 테이블 생성
- [x] 지출 JPA 연결
